[package]
name = "mesh_tools_py"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
sdl2 = "0.35.2"
gl = "0.14.0"
ultraviolet = { version = "0.6", features = [ "f64", "int" ] }
image = "0.24.4"

[build-dependencies]
gl_generator = "0.14.0"
